import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import { Navbar } from '@/components';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

 const style = { 
  display: "flex", 
  flexDirection: "row",
  background: "linear-gradient(to right, #ffffff, #f2f2f2)",
};

  return (
    <html lang="en">
      <head>
        {/* Mettere qui i tuoi metadati */}
      </head>
      <body className={inter.className} style={style}>
        <Navbar style={{ position: "fixed", left: 0, top: 0, height: "100vh" }} />
        <div style={{ marginLeft: "30px", width: "calc(100% - 200px)", padding:'20px' }}>
          {children}
        </div>
      </body>
    </html>
  );
}
